### ISSUE TITLE
Does not support native GitHub Pages MermaidJs support.

### ISSUE THREAD

**Issue by duaneking** [actions/jekyll-build-pages#39]
I want to be able to copy and paste a index.md file from a GitHub repo where it renders with MermaidJS just fine, and have it render effectively the same diagram after being rendered on GH Pages.

The current build system actively corrupts Mermaid rendered files and makes them impossible to render as expected.

The fact that safe=true is hard coded means we cant add a plugin that would support this to the default pipeline without githubs help.

I'm trying to support efforts for the blind to be able to more easily communicate visual ideas to the sighted and this support is critical to allow that using MermaidJS.  I am formally asking for all reasonable accommodation from GitHub and developers to support this goal.

**Comment by JamesMGreene** [comment]
@duaneking It seems unlikely [to me] that this will get added into the implicit GitHub Pages builds as that configuration has rarely changed in any meaningful way.

However, we have recently done [a **beta** release](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) adding the ability to customize your Pages deployments completely if you're willing to use GitHub Actions as your build-and-deployment mechanism with a custom workflow rather than relying on the implicit GitHub Pages functionality.

Here's an example starter workflow for building with Ruby `3.x` and whichever version of Jekyll you have configured (vs. being stuck on Jekyll `3.x` with the implicit GitHub Pages builds):
https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml

This would allow you to customize our site with any Jekyll plugins you'd like since the build configuration is left entirely up to you. 👍🏻

**Comment by duaneking** [comment]
No. You dont get it.

Your just asking the blind to do more work.
